version: '3'

services:
  db:
    image: mongo:5
    restart: always
    ports:
      - 27020:27017 # puerto de mi pc : puerto del contenedor
    environment:
      MONGODB_DATABASE: product-nestjs
    volumes:
      - ./mongo:/data/db
